name: Lint Code Base
on:
  push:
    branches-ignore:
      - 'master2'
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: docker://github/super-linter:v3.17.1
